# .goreleaser.yaml
version: 2

project_name: tailscale-proxy-app

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    main: .
    flags:
      - -tags=urfave_cli_no_docs
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
      - goos: windows
        goarch: amd64
        env:
          - CC=/llvm-mingw/bin/x86_64-w64-mingw32-gcc
          - CXX=/llvm-mingw/bin/x86_64-w64-mingw32-g++
      - goos: windows
        goarch: arm64
        env:
          - CC=/llvm-mingw/bin/aarch64-w64-mingw32-gcc
          - CXX=/llvm-mingw/bin/aarch64-w64-mingw32-g++

  - id: macos
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    flags:
      - -tags=urfave_cli_no_docs
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    overrides:
      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
          - CXX=o64-clang++
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
          - CXX=oa64-clang++

archives:
  - builds:
      - default
      - macos
    formats:
      - tar.gz
    # this name template makes the OS and Arch compatible with what users expect
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

nfpms:
  - maintainer: Egor Kotov <e.kotov@gmail.com>
    description: Standalone userspace egress proxy for Tailscale exit nodes (no root required). It exposes a local HTTP/SOCKS5 proxy that routes traffic through any of your tailnet's exit nodes.
    homepage: https://github.com/e-kotov/tailscale-proxy-app
    license: BSD-3-Clause
    formats:
      - deb
      - rpm
    overrides:
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
      rpm:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"

brews:
  - repository:
      owner: e-kotov
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/e-kotov/tailscale-proxy-app
    description: Standalone userspace egress proxy for Tailscale exit nodes (no root required). It exposes a local HTTP/SOCKS5 proxy that routes traffic through any of your tailnet's exit nodes.
    license: BSD-3-Clause
    test: |
      system "#{bin}/tailscale-proxy-app --version"

scoops:
  - repository:
      owner: e-kotov
      name: homebrew-tap
    directory: bucket
    homepage: https://github.com/e-kotov/tailscale-proxy-app
    description: Standalone userspace egress proxy for Tailscale exit nodes (no root required). It exposes a local HTTP/SOCKS5 proxy that routes traffic through any of your tailnet's exit nodes.
    license: BSD-3-Clause

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
